on:
  push:
    paths: ['**.R', 'tests/**', '**.Rd', '**.c', '**.cpp', '**.h', '**.hpp', 'DESCRIPTION', 'NAMESPACE', 'MAKEVARS', 'MAKEVARS.win', '**.yml']
  pull_request:
    paths: ['**.R', 'tests/**', '**.Rd', '**.c', '**.cpp', '**.h', '**.hpp', 'DESCRIPTION', 'NAMESPACE', 'MAKEVARS', 'MAKEVARS.win']
  schedule:
    - cron:  '13 12 * * 1-5'

name: unit-tests

jobs:

  unit-tests:

    uses: jasp-stats/jasp-actions/.github/workflows/unittests.yml@master
    with:
      needs_JAGS:   true
      needs_igraph: false
